using Aristotle.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Aristotle.Infrastructure.Persistence.Configurations;

/// <summary>
///     Entity Framework Core configuration for the User entity using Fluent API.
///     This separates persistence concerns from the domain model.
/// </summary>
public class UserConfiguration : IEntityTypeConfiguration<User>
{
    /// <summary>
    ///     Configures the User entity mapping.
    /// </summary>
    /// <param name="builder">The entity type builder.</param>
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.HasKey(u => u.ExternalUserId);

        // ExternalUserId is provided by the application (from Keycloak 'sub' claim)
        // and should never be generated by the database
        builder.Property(u => u.ExternalUserId).IsRequired().ValueGeneratedNever();

        builder.Property(u => u.CreatedAt).IsRequired().HasDefaultValueSql("NOW()");

        // Index for faster lookups
        builder.HasIndex(u => u.ExternalUserId).IsUnique();

        builder.HasIndex(u => u.CreatedAt);
    }
}